/*
 * Smart CI — internationalization (i18n) layer.
 * Provides language selection (English / Brazilian Portuguese), a UI string
 * dictionary, locale-aware number/date formatting, and module-content
 * selection. Loaded BEFORE app.js / exam.js on every page.
 *
 * Language preference is persisted inside the existing prefs object
 * (localStorage key "CISmartCiPrefs") under the "lang" field so it travels
 * with the role/flow/belt choices set in onboarding.
 */
(function () {
  "use strict";

  var PREF_KEY = "CISmartCiPrefs";
  var SUPPORTED = ["en", "pt-BR", "es-419"];

  function readPrefs() {
    try { return JSON.parse(window.localStorage.getItem(PREF_KEY)) || {}; }
    catch (e) { return {}; }
  }
  function writePrefs(p) {
    try { window.localStorage.setItem(PREF_KEY, JSON.stringify(p)); } catch (e) { /* ignore */ }
  }
  function normLang(v) { return SUPPORTED.indexOf(v) >= 0 ? v : null; }

  function getLang() { return normLang(readPrefs().lang) || "en"; }
  function setLang(l) {
    var p = readPrefs();
    p.lang = normLang(l) || "en";
    writePrefs(p);
  }
  function locale() {
    var l = getLang();
    if (l === "pt-BR") return "pt-BR";
    if (l === "es-419") return "es-419";
    return "en-US";
  }
  function langName(l) {
    var key = normLang(l) || getLang();
    if (key === "pt-BR") return "Portugu\u00eas (Brasil)";
    if (key === "es-419") return "Espa\u00f1ol (Latinoam\u00e9rica)";
    return "English";
  }

  /* ---------------- Locale-aware formatting ---------------- */
  function fmtNumber(n, opts) {
    try { return new Intl.NumberFormat(locale(), opts).format(n); }
    catch (e) { return String(n); }
  }
  function fmtPercent(fraction, fractionDigits) {
    try {
      return new Intl.NumberFormat(locale(), {
        style: "percent",
        maximumFractionDigits: fractionDigits == null ? 0 : fractionDigits
      }).format(fraction);
    } catch (e) { return Math.round(fraction * 100) + "%"; }
  }
  function fmtDate(d, opts) {
    var date = d instanceof Date ? d : new Date(d);
    try { return new Intl.DateTimeFormat(locale(), opts || { dateStyle: "long" }).format(date); }
    catch (e) { return date.toLocaleDateString(); }
  }

  /* ---------------- Module content selection ---------------- */
  function getModules() {
    var l = getLang();
    if (l === "pt-BR" && window.MODULES_PT) return window.MODULES_PT;
    if (l === "es-419" && window.MODULES_ES) return window.MODULES_ES;
    return window.MODULES || {};
  }

  /* ---------------- UI string dictionary ----------------
     Keys are dot-namespaced. Values may contain HTML when used with
     data-i18n-html or the {html:true} option. Missing pt-BR keys fall
     back to English so the site never renders a blank string. */
  var DICT = {
    en: {
      "telemetry.aria": "Usage data preference",
      "telemetry.message": "Allow anonymous usage data to help improve this learning experience. No names, answers, or feedback text are collected.",
      "telemetry.deny": "No thanks",
      "telemetry.allow": "Allow",

      /* shared chrome */
      "internal.notice": "<strong>Internal &amp; proposed &mdash; not an official Microsoft offering.</strong> &ldquo;CI-900&rdquo; and this delivery series are an internal proposal at this time, intended for an internal audience only. They are not a Microsoft product, certification, or exam, and are not affiliated with, endorsed by, or sponsored by Microsoft. Do not share externally.",
      "internal.notice.exam": "<strong>Internal &amp; proposed &mdash; not an official Microsoft offering.</strong> &ldquo;CI-900&rdquo; is an internal proposal at this time, intended for an internal audience only. It is not a Microsoft certification or exam and is not affiliated with, endorsed by, or sponsored by Microsoft. Do not share externally.",
      "breadcrumb.series": "Smart CI \u2014 30-Minute Delivery Series",
      "breadcrumb.module": "Module",
      "breadcrumb.exam": "CI-900 Practice Exam",
      "footer.index": "Smart CI Tools \u00b7 30-Minute Delivery Series \u00b7 Internal &amp; proposed \u2014 not an official Microsoft offering \u00b7 Built from the CI for CI knowledge base",
      "footer.module": "Smart CI Tools \u00b7 30-Minute Delivery Series",
      "footer.exam": "Smart CI Tools \u00b7 CI-900 Practice Exam \u00b7 Proposed, internal-only concept \u2014 not an official Microsoft offering \u00b7 Unofficial practice assessment built from the CI for CI knowledge base",

      /* index hero */
      "index.title": "Smart CI \u2014 30-Minute Delivery Series",
      "hero.eyebrow": "CI \u00b7 in \u00b7 30",
      "hero.title": "Continuous Improvement \u2014 30-Minute Delivery Series",
      "hero.lede": "Every Lean Six Sigma topic in the Smart CI library, repackaged into bite-sized 30-minute sessions. Choose your role and pick a path &mdash; a <strong>guided progression</strong> from the most basic concepts to the most advanced, <strong>browse by concept</strong> and category, or <strong>follow a belt</strong> to filter the library to the learning plan for the Lean Six Sigma belt you&rsquo;re pursuing. Each module opens with an executive summary, states what you&rsquo;ll gain in plain language, explains the concept, shows role-based examples for CSAMs and CSAs, recaps the key takeaways, and closes with a Microsoft certification&ndash;style knowledge check.",
      "hero.stat.modules": "30-min modules",
      "hero.stat.roles": "roles: CSAM &amp; CSA",
      "hero.stat.parts": "parts per module",
      "hero.stat.questions": "knowledge-check questions",

      /* format section */
      "format.heading": "How each 30-minute module is structured",
      "format.part1.label": "Executive Summary", "format.part1.desc": "Why the session matters, for leaders.",
      "format.part2.label": "What You\u2019ll Gain", "format.part2.desc": "Plain-language outcomes.",
      "format.part3.label": "The Topic", "format.part3.desc": "The concept, explained.",
      "format.part4.label": "Role Examples", "format.part4.desc": "CSAM &amp; CSA scenarios.",
      "format.part5.label": "Recap", "format.part5.desc": "Key concepts &amp; takeaways.",
      "format.part6.label": "Knowledge Check", "format.part6.desc": "MS cert\u2013style quiz.",
      "format.part": "PART",

      /* exam CTA on index */
      "examcta.eyebrow": "Test your readiness",
      "examcta.title": "CI-900: Continuous Improvement Fundamentals",
      "examcta.desc": "A practice exam in the <em>style</em> of a Microsoft certification, over the whole library. Use <strong>Practice mode</strong> to learn with instant feedback, or <strong>Certification mode</strong> for a timed, scaled-scored attempt with a mark-for-review screen and skill-area report. <strong>CI-900 is a proposed, internal-only concept &mdash; not a real Microsoft certification or exam.</strong>",
      "examcta.btn": "Take the practice exam \u2192",

      /* onboarding */
      "onb.eyebrow": "Smart CI \u00b7 Set up your path",
      "onb.title": "Welcome \u2014 let\u2019s tailor this to you",
      "onb.lede": "Choose your language, your role, and how you\u2019d like to move through the material. You can change all three at any time.",
      "onb.q.lang": "1. Which language would you like?",
      "onb.lang.en.title": "English",
      "onb.lang.en.desc": "Content and interface in English (US formatting).",
      "onb.lang.pt.title": "Portugu\u00eas (Brasil)",
      "onb.lang.pt.desc": "Conte\u00fado e interface em portugu\u00eas, com formata\u00e7\u00e3o do Brasil.",
      "onb.lang.es.title": "Espa\u00f1ol (Latinoam\u00e9rica)",
      "onb.lang.es.desc": "Contenido e interfaz en espa\u00f1ol neutro, con formato latinoamericano.",
      "onb.q.role": "2. What is your role?",
      "onb.role.csam.title": "CSAM",
      "onb.role.csam.desc": "Customer Success Account Manager. Examples and scenarios default to the CSAM view.",
      "onb.role.csa.title": "CSA",
      "onb.role.csa.desc": "Cloud Solution Architect. Examples and scenarios default to the CSA view.",
      "onb.role.customer.title": "Customer",
      "onb.role.customer.desc": "The customer's point of view. See how continuous improvement lands for your team \u2014 no CSA or CSAM hat required.",
      "onb.role.practitioner.title": "CI Practitioner",
      "onb.role.practitioner.desc": "A general continuous-improvement practitioner. Examples focus on applying Lean Six Sigma in your own team, independent of role.",
      "onb.role.sss.title": "Services Solutions Seller",
      "onb.role.sss.desc": "Sell Microsoft services outcomes. Examples focus on qualifying, positioning and closing engagements tied to measurable value.",
      "onb.role.sae.title": "Services Account Executive",
      "onb.role.sae.desc": "Own the services account. Examples focus on account planning, executive stakeholders, scope, margin and renewals.",
      "onb.role.tas.title": "Technical Account Strategist",
      "onb.role.tas.desc": "The trusted technical advisor. Examples focus on technical health, proactive risk and the customer's improvement roadmap.",
      "onb.q.flow": "3. How would you like to explore?",
      "onb.flow.guided.title": "Guided path",
      "onb.flow.guided.desc": "A single progression from the most basic ideas to the most advanced. Best if you are newer to Lean Six Sigma.",
      "onb.flow.concept.title": "Browse by concept",
      "onb.flow.concept.desc": "Modules grouped into categories so you can jump to whatever topic you need.",
      "onb.flow.belt.title": "Follow a belt",
      "onb.flow.belt.desc": "Pursue a Lean Six Sigma belt. Pick your target belt and we filter the library to that belt\u2019s learning plan.",
      "onb.q.belt": "4. Which belt are you pursuing?",
      "onb.start": "Start learning",
      "onb.next": "Next",
      "onb.back": "Back",
      "onb.step": "Step {n} of {total}",
      "onb.aria": "Set up your path",

      /* prefbar */
      "prefbar.showing": "Showing the",
      "prefbar.for": "view for",
      "prefbar.flow.guided": "Guided path",
      "prefbar.flow.concept": "Browse by concept",
      "prefbar.flow.beltSuffix": "plan",
      "prefbar.toggle.guided": "Guided path",
      "prefbar.toggle.concept": "By concept",
      "prefbar.toggle.belt": "By belt",
      "prefbar.change": "Change language / role / path",
      "prefbar.targetBelt": "Target belt",
      "prefbar.aria.flow": "Choose flow",
      "prefbar.aria.belt": "Choose target belt",

      /* index listings */
      "index.modulesEach": "30 min each",
      "index.module": "module", "index.modules": "modules",
      "card.questionCheck": "-question check",
      "card.beltReq": "Required knowledge for",
      "label.step": "STEP", "label.module": "MODULE",

      /* belt index */
      "belt.plan.eyebrow": "Belt learning plan",
      "belt.workingToward": "Working toward your",
      "belt.inThisPlan": "in this plan",
      "belt.cumulativeThrough": "cumulative through",
      "belt.ofStudy": "of study",
      "belt.yourTarget": "Your target",
      "belt.prerequisite": "Prerequisite",
      "belt.beyond": "Beyond",
      "belt.moreModule": "more module", "belt.moreModules": "more modules",
      "belt.cumulativeNote": "Belts are cumulative \u2014 selecting a higher belt keeps everything here and adds the deeper material.",

      /* module page */
      "module.titleSuffix": "Smart CI Delivery",
      "module.delivery": "delivery",
      "module.questionCheck": "-question knowledge check",
      "module.flow.guided": "Guided path",
      "module.flow.concept": "By concept",
      "module.flow.beltSuffix": "plan",
      "module.posOf": "of",
      "module.beyondPlan": "beyond this plan",
      "module.notFound": "Module not found. ",
      "module.returnAll": "Return to all modules.",
      "sec.exec.kicker": "Executive Summary", "sec.exec.title": "Why this 30 minutes matters",
      "sec.gain.kicker": "What You'll Gain", "sec.gain.title": "What you'll walk away able to do",
      "sec.topic.kicker": "The Topic", "sec.topic.title": "The concept, explained",
      "sec.roles.kicker": "Role-Based Examples", "sec.roles.title": "How it looks in the field",
      "sec.recap.kicker": "Recap", "sec.recap.title": "Key concepts & takeaways",
      "audio.kicker": "Conversational audio",
      "audio.intro.title": "Hear the six-week PDCA improvement cadence",
      "audio.intro.description": "Prefer to listen? This conversational explanation walks through the module's six-week improvement cadence and how a CI practitioner keeps the PDCA loop moving.",
      "audio.intro.meta": "5 min 15 sec · English audio",
      "audio.intro.aria": "Conversational explanation of the six-week PDCA improvement cadence",
      "audio.intro.link": "Listen to audio summary",
      "audio.fallback": "Download the audio explanation.",
      "role.tab.csam": "CSAM \u2014 Customer Success Account Manager",
      "role.tab.csa": "CSA \u2014 Cloud Solution Architect",
      "role.tab.customer": "Customer \u2014 your team's point of view",
      "role.tab.practitioner": "CI Practitioner \u2014 continuous improvement in practice",
      "role.tab.sss": "Services Solutions Seller \u2014 selling improvement outcomes",
      "role.tab.sae": "Services Account Executive \u2014 owning the account",
      "role.tab.tas": "Technical Account Strategist \u2014 the technical roadmap",
      "role.panel.csam": "CSAM \u00b7 Customer Success Account Manager",
      "role.panel.csa": "CSA \u00b7 Cloud Solution Architect",
      "role.panel.customer": "Customer \u00b7 your team's point of view",
      "role.panel.practitioner": "CI Practitioner \u00b7 continuous improvement in practice",
      "role.panel.sss": "Services Solutions Seller \u00b7 selling improvement outcomes",
      "role.panel.sae": "Services Account Executive \u00b7 owning the account",
      "role.panel.tas": "Technical Account Strategist \u00b7 the technical roadmap",
      "role.short.customer": "Customer",
      "role.short.practitioner": "CI Practitioner",
      "role.short.sss": "Services Solutions Seller",
      "role.short.sae": "Services Account Executive",
      "role.short.tas": "Technical Account Strategist",
      "module.prev": "\u2190 Previous module",
      "module.next": "Next module \u2192",

      /* knowledge check */
      "kc.kicker": "Knowledge Check",
      "kc.title": "Test your understanding",
      "kc.intro": "Microsoft certification\u2013style questions. Commit to an answer to reveal the explanation.",
      "kc.questions": "Questions:", "kc.pass": "Pass:",
      "q.indexOf1": "Question", "q.indexOf2": "of",
      "q.check": "Check answer",
      "q.markerCorrect": "\u2713 Correct answer",
      "q.markerYour": "\u2715 Your answer",
      "q.fb.correct": "Correct", "q.fb.notquite": "Not quite",
      "kc.summary.pass": "Knowledge check complete",
      "kc.summary.retry": "Almost there",
      "kc.summary.passed": "You passed. Review any items you missed.",
      "kc.summary.failedPrefix": "Passing score is",
      "kc.summary.failedSuffix": ". Review the module and try again.",
      "kc.retry": "Retry knowledge check",
      "kc.allModules": "All modules",

      /* points */
      "points.kicker": "Progress",
      "points.title": "Your points",
      "points.subtitle": "Every module is worth 100 points. Pass a knowledge check and you earn points in proportion to your score \u2014 80% earns 80 points.",
      "points.total": "Total points",
      "points.byBelt": "Points by belt",
      "points.modulesScored": "modules scored",
      "points.modules": "modules",
      "points.pts": "pts",
      "points.worth": "Worth",
      "points.newBest": "New best",
      "points.summary.earned": "Points earned",
      "points.empty": "No points yet \u2014 pass a knowledge check to start earning toward your belts.",
      "points.reset": "Reset points",
      "points.reset.confirm": "Reset all earned points? This can\u2019t be undone.",
      "exam.hero.eyebrow": "Microsoft certification\u2013style practice assessment",
      "exam.hero.lede": "A realistic, exam-style assessment over the entire Smart CI library. Choose Practice mode to learn with instant feedback, or Certification mode for a timed, scored attempt that mirrors the real testing experience.",
      "exam.fact.bank": "questions in the bank",
      "exam.fact.perAttempt": "per certification attempt",
      "exam.fact.timeLimit": "time limit (cert mode)",
      "exam.fact.scoreToPass": "score to pass",
      "exam.q.short": "Q", "exam.min": "min",
      "exam.practice.badge": "Practice / Prep mode",
      "exam.practice.title": "Learn with instant feedback",
      "exam.practice.desc": "One question at a time. Commit to an answer and the correct choice and full explanation appear immediately. Untimed \u2014 ideal for building knowledge before a timed run.",
      "exam.practice.li1": "Immediate answer + rationale after each item",
      "exam.practice.li2": "Focus on a single skill area or the whole bank",
      "exam.practice.li3": "No timer, retake as often as you like",
      "exam.practice.start": "Start practice",
      "exam.field.length": "Length", "exam.field.skill": "Skill area",
      "exam.len.questions": "questions",
      "exam.len.all": "All", "exam.len.allSuffix": "questions",
      "exam.skill.all": "All skill areas",
      "exam.cap.msg": "The \u201c{skill}\u201d skill area has only {avail} question(s) available \u2014 fewer than the {req} you selected. Start with the maximum {avail} available?",
      "exam.cert.badge": "Certification mode",
      "exam.cert.title": "Timed, scored, exam-realistic",
      "exam.cert.start": "Start certification exam",
      "exam.name": "Continuous Improvement Fundamentals",
      "exam.cert.desc": "{len} questions in {min} minutes. No feedback until you submit. Mark items for review, revisit them from a review screen, then receive a scaled score and a skill-area breakdown \u2014 exactly like a Microsoft certification exam.",
      "exam.cert.li1": "{len} questions \u00b7 {min}-minute countdown",
      "exam.cert.li3": "Scaled score out of {max} \u00b7 pass at {pass}",
      "exam.cert.markLi": "Mark for review + end-of-exam review grid",
      "exam.cert.reportLi": "Per\u2013skill-area performance report",
      "exam.skills.title": "Skills measured",
      "exam.skills.note": "A certification attempt samples questions across these skill areas using the listed weightings.",
      "exam.skills.col.area": "Skill area", "exam.skills.col.weight": "Weighting", "exam.skills.col.bank": "Bank",
      "exam.disclaimer": "This is an unofficial, internal practice assessment built from the Smart CI knowledge base to mimic the format of Microsoft certification exams. CI-900 is a proposed, internal-only concept at this time, for an internal audience only. It is not affiliated with or endorsed by Microsoft, and is not a real Microsoft exam or certification.",

      /* exam session */
      "exam.mode.cert": "Certification mode", "exam.mode.practice": "Practice mode",
      "exam.bar.question": "Question", "exam.bar.of": "of", "exam.bar.answered": "answered",
      "exam.endPractice": "End practice",
      "exam.question": "Question",
      "exam.chooseBest": "Choose the best answer.",
      "exam.prev": "\u2190 Previous", "exam.next": "Next \u2192",
      "exam.markReview": "Mark for review",
      "exam.review.btn": "Review \u2630",
      "exam.reviewSubmit": "Review & submit", "exam.finish": "Finish",
      "exam.reviewScreen": "Review screen",
      "exam.review.title": "Review your answers",
      "exam.review.note": "Select any question to return to it. Items you flagged are marked. Unanswered questions are scored as incorrect.",
      "exam.legend.answered": "Answered", "exam.legend.unanswered": "Unanswered", "exam.legend.marked": "Marked for review",
      "exam.allAnswered": "All questions answered.",
      "exam.stillUnanswered1": "question still unanswered.", "exam.stillUnanswered2": "questions still unanswered.",
      "exam.markedForReview": "marked for review.",
      "exam.returnQuestions": "\u2190 Return to questions",
      "exam.submit": "Submit exam",
      "exam.confirm.unanswered1": "You have", "exam.confirm.unanswered2": "unanswered question",
      "exam.confirm.unanswered2p": "unanswered questions",
      "exam.confirm.anyway": ". Submit anyway? Unanswered items are scored as incorrect.",
      "exam.confirm.submit": "Submit your exam for scoring?",
      "exam.confirm.endPractice": "End this practice session and see your results?",

      /* exam report */
      "exam.attempt": "Certification attempt", "exam.session": "Practice session",
      "exam.pass": "PASS", "exam.fail": "DID NOT PASS",
      "exam.passingScore": "Passing score:",
      "exam.passLine": "pass",
      "exam.correctSuffix": "correct",
      "exam.ofCorrect": "correct \u00b7 time used",
      "exam.timeExpired": "Time expired \u00b7",
      "exam.attemptedOn": "Attempted on",
      "exam.breakdown.title": "Performance by skill area",
      "exam.answers.review": "Review all questions & explanations",
      "exam.answers.hide": "Hide question review",
      "exam.retakeCert": "Retake certification exam", "exam.newPractice": "New practice session",
      "exam.backModules": "Back to modules",
      "exam.answer.correct": "Correct", "exam.answer.incorrect": "Incorrect", "exam.answer.unanswered": "Unanswered",
      "exam.answer.markCorrect": " \u2713 Correct answer", "exam.answer.markYour": " \u2715 Your answer", "exam.answer.markYourCorrect": " \u2713 Your answer",
      "exam.answer.explanation": "Explanation:",
      "exam.noQuestions": "No questions available.",

      /* group / stage / belt display names */
      "group.Foundations": "Foundations",
      "group.Methodologies & Cycles": "Methodologies & Cycles",
      "group.Value & Quality Definition": "Value & Quality Definition",
      "group.Process Mapping & Analysis": "Process Mapping & Analysis",
      "group.Workplace, Flow & Standardization": "Workplace, Flow & Standardization",
      "group.Measurement & Control": "Measurement & Control",
      "group.Strategy & Governance": "Strategy & Governance",

      "stage.1": "Stage 1 \u00b7 Start Here \u2014 What CI Is",
      "stage.2": "Stage 2 \u00b7 See Value and Waste",
      "stage.3": "Stage 3 \u00b7 Organize and Standardize",
      "stage.4": "Stage 4 \u00b7 Improve in Cycles",
      "stage.5": "Stage 5 \u00b7 Map and Analyze the Process",
      "stage.6": "Stage 6 \u00b7 Find the Root Cause",
      "stage.7": "Stage 7 \u00b7 Balance the Flow",
      "stage.8": "Stage 8 \u00b7 Measure with Data",
      "stage.9": "Stage 9 \u00b7 Prove It Statistically",
      "stage.10": "Stage 10 \u00b7 Lead and Govern",

      "belt.white.name": "White Belt", "belt.white.tagline": "Awareness & vocabulary",
      "belt.white.goal": "Know the language of continuous improvement and recognize the core tools \u2014 you understand what they are and why they matter, even before you run them.",
      "belt.yellow.name": "Yellow Belt", "belt.yellow.tagline": "Practitioner \u2014 contribute to improvements",
      "belt.yellow.goal": "Take part in improvement events: run 5 Whys on a confirmed problem, contribute to an Ishikawa, and support standard work and error-proofing.",
      "belt.green.name": "Green Belt", "belt.green.tagline": "Lead small-to-medium projects",
      "belt.green.goal": "Run DMAIC projects end-to-end with process mapping, flow balancing, and basic statistics.",
      "belt.black.name": "Black Belt", "belt.black.tagline": "Lead programs, mentor & govern",
      "belt.black.goal": "Lead cross-functional programs with deep statistics, risk analysis, and CI strategy \u2014 and mentor Green Belts.",
      "belt.hoursSuffix": "hours",

      "domain.foundations": "Describe continuous-improvement foundations and concepts",
      "domain.methods": "Apply improvement methodologies and cycles",
      "domain.value": "Define customer value and quality",
      "domain.mapping": "Map and analyze processes and root causes",
      "domain.flow": "Optimize workplace, flow, and standardization",
      "domain.measure": "Measure and control processes statistically",
      "domain.govern": "Lead CI strategy and governance",

      /* feedback (Voice of Customer) */
      "voc.button": "Feedback",
      "voc.aria": "Share your feedback",
      "voc.title": "Share your feedback",
      "voc.lede": "Help us improve the 30-Minute Delivery Series. Your feedback is collected as a Voice-of-Customer issue in the project&rsquo;s GitHub repository.",
      "voc.github.note": "Submitting opens a pre-filled GitHub issue in a new tab &mdash; review it, then click <strong>Submit new issue</strong> to send. A GitHub account with access to the repository is required.",
      "voc.type.label": "What kind of feedback is this?",
      "voc.type.content": "Content accuracy",
      "voc.type.suggestion": "Suggestion or improvement",
      "voc.type.bug": "Bug or broken link",
      "voc.type.question": "Question",
      "voc.type.praise": "Praise",
      "voc.type.other": "Other",
      "voc.rating.label": "Overall rating (optional)",
      "voc.rating.clear": "Clear rating",
      "voc.subject.label": "Summary",
      "voc.subject.ph": "A short title for your feedback",
      "voc.details.label": "Details",
      "voc.details.ph": "What worked, what didn\u2019t, and any suggestions\u2026",
      "voc.name.label": "Your name (optional)",
      "voc.name.ph": "So we can follow up, if needed",
      "voc.required": "Please add a summary and some details before submitting.",
      "voc.submit": "Open GitHub issue",
      "voc.cancel": "Cancel",
      "survey.exam.eyebrow": "Quick survey",
      "survey.exam.title": "How was this assessment?",
      "survey.exam.lede": "A few quick questions help us improve the CI-900 practice exam.",
      "survey.exam.q.label": "How did the difficulty feel?",
      "survey.exam.q.easy": "Too easy",
      "survey.exam.q.right": "About right",
      "survey.exam.q.hard": "Too hard",
      "survey.belt.eyebrow": "Belt complete \u00b7 Quick survey",
      "survey.belt.title": "You\u2019ve reached the end of the {belt} plan",
      "survey.belt.lede": "Congratulations! Tell us how this belt worked for you so we can improve it.",
      "survey.belt.q.label": "How confident do you feel applying these tools?",
      "survey.belt.q.low": "Not yet confident",
      "survey.belt.q.mid": "Getting there",
      "survey.belt.q.high": "Confident",
      "survey.rating.label": "Overall, how would you rate it?",
      "survey.comment.label": "Anything you\u2019d add? (optional)",
      "survey.comment.ph": "What worked, what didn\u2019t, and any suggestions\u2026",
      "survey.github.note": "Submitting opens a pre-filled GitHub issue in a new tab &mdash; review it, then click <strong>Submit new issue</strong> to send. A GitHub account with access to the repository is required.",
      "survey.required": "Please add an overall rating before submitting.",
      "survey.submit": "Submit survey",
      "survey.dismiss": "No thanks",
      "survey.thanks.title": "Thank you!",
      "survey.thanks.body": "Your feedback helps us improve the 30-Minute Delivery Series."
    },

    "pt-BR": {
      "telemetry.aria": "Preferência de dados de uso",
      "telemetry.message": "Permita a coleta de dados de uso anônimos para ajudar a melhorar esta experiência de aprendizagem. Nenhum nome, resposta ou texto de comentário é coletado.",
      "telemetry.deny": "Agora não",
      "telemetry.allow": "Permitir",

      /* shared chrome */
      "internal.notice": "<strong>Interno e proposto &mdash; n\u00e3o \u00e9 uma oferta oficial da Microsoft.</strong> &ldquo;CI-900&rdquo; e esta s\u00e9rie de entrega s\u00e3o, neste momento, uma proposta interna destinada apenas a um p\u00fablico interno. N\u00e3o s\u00e3o um produto, certifica\u00e7\u00e3o ou exame da Microsoft e n\u00e3o s\u00e3o afiliados, endossados ou patrocinados pela Microsoft. N\u00e3o compartilhe externamente.",
      "internal.notice.exam": "<strong>Interno e proposto &mdash; n\u00e3o \u00e9 uma oferta oficial da Microsoft.</strong> &ldquo;CI-900&rdquo; \u00e9, neste momento, uma proposta interna destinada apenas a um p\u00fablico interno. N\u00e3o \u00e9 uma certifica\u00e7\u00e3o ou exame da Microsoft e n\u00e3o \u00e9 afiliada, endossada ou patrocinada pela Microsoft. N\u00e3o compartilhe externamente.",
      "breadcrumb.series": "Smart CI \u2014 S\u00e9rie de Entregas de 30 Minutos",
      "breadcrumb.module": "M\u00f3dulo",
      "breadcrumb.exam": "Exame Pr\u00e1tico CI-900",
      "footer.index": "Smart CI Tools \u00b7 S\u00e9rie de Entregas de 30 Minutos \u00b7 Interno e proposto \u2014 n\u00e3o \u00e9 uma oferta oficial da Microsoft \u00b7 Constru\u00eddo a partir da base de conhecimento CI for CI",
      "footer.module": "Smart CI Tools \u00b7 S\u00e9rie de Entregas de 30 Minutos",
      "footer.exam": "Smart CI Tools \u00b7 Exame Pr\u00e1tico CI-900 \u00b7 Conceito proposto e somente interno \u2014 n\u00e3o \u00e9 uma oferta oficial da Microsoft \u00b7 Avalia\u00e7\u00e3o pr\u00e1tica n\u00e3o oficial constru\u00edda a partir da base de conhecimento CI for CI",

      /* index hero */
      "index.title": "Smart CI \u2014 S\u00e9rie de Entregas de 30 Minutos",
      "hero.eyebrow": "CI \u00b7 in \u00b7 30",
      "hero.title": "Melhoria Cont\u00ednua \u2014 S\u00e9rie de Entregas de 30 Minutos",
      "hero.lede": "Todos os t\u00f3picos de Lean Six Sigma da biblioteca Smart CI, reempacotados em sess\u00f5es objetivas de 30 minutos. Escolha sua fun\u00e7\u00e3o e um caminho &mdash; uma <strong>progress\u00e3o guiada</strong> dos conceitos mais b\u00e1sicos aos mais avan\u00e7ados, <strong>navegue por conceito</strong> e categoria, ou <strong>siga uma faixa</strong> para filtrar a biblioteca pelo plano de aprendizado da faixa de Lean Six Sigma que voc\u00ea busca. Cada m\u00f3dulo abre com um resumo executivo, descreve o que voc\u00ea vai ganhar em linguagem simples, explica o conceito, mostra exemplos por fun\u00e7\u00e3o para CSAMs e CSAs, recapitula os pontos-chave e encerra com uma verifica\u00e7\u00e3o de conhecimento no estilo das certifica\u00e7\u00f5es da Microsoft.",
      "hero.stat.modules": "m\u00f3dulos de 30 min",
      "hero.stat.roles": "fun\u00e7\u00f5es: CSAM &amp; CSA",
      "hero.stat.parts": "partes por m\u00f3dulo",
      "hero.stat.questions": "quest\u00f5es de verifica\u00e7\u00e3o",

      /* format section */
      "format.heading": "Como cada m\u00f3dulo de 30 minutos \u00e9 estruturado",
      "format.part1.label": "Resumo Executivo", "format.part1.desc": "Por que a sess\u00e3o importa, para l\u00edderes.",
      "format.part2.label": "O Que Voc\u00ea Vai Ganhar", "format.part2.desc": "Resultados em linguagem simples.",
      "format.part3.label": "O Tema", "format.part3.desc": "O conceito, explicado.",
      "format.part4.label": "Exemplos por Fun\u00e7\u00e3o", "format.part4.desc": "Cen\u00e1rios de CSAM &amp; CSA.",
      "format.part5.label": "Recapitula\u00e7\u00e3o", "format.part5.desc": "Conceitos-chave &amp; li\u00e7\u00f5es.",
      "format.part6.label": "Verifica\u00e7\u00e3o de Conhecimento", "format.part6.desc": "Quiz no estilo de certifica\u00e7\u00e3o MS.",
      "format.part": "PARTE",

      /* exam CTA on index */
      "examcta.eyebrow": "Teste sua prepara\u00e7\u00e3o",
      "examcta.title": "CI-900: Fundamentos da Melhoria Cont\u00ednua",
      "examcta.desc": "Um exame pr\u00e1tico no <em>estilo</em> de uma certifica\u00e7\u00e3o da Microsoft, cobrindo toda a biblioteca. Use o <strong>modo Pr\u00e1tica</strong> para aprender com feedback imediato, ou o <strong>modo Certifica\u00e7\u00e3o</strong> para uma tentativa cronometrada com pontua\u00e7\u00e3o em escala, tela de marca\u00e7\u00e3o para revis\u00e3o e relat\u00f3rio por \u00e1rea de compet\u00eancia. <strong>O CI-900 \u00e9 um conceito proposto e somente interno &mdash; n\u00e3o \u00e9 uma certifica\u00e7\u00e3o ou exame real da Microsoft.</strong>",
      "examcta.btn": "Fazer o exame pr\u00e1tico \u2192",

      /* onboarding */
      "onb.eyebrow": "Smart CI \u00b7 Configure seu caminho",
      "onb.title": "Bem-vindo(a) \u2014 vamos personalizar isto para voc\u00ea",
      "onb.lede": "Escolha seu idioma, sua fun\u00e7\u00e3o e como prefere percorrer o material. Voc\u00ea pode alterar os tr\u00eas a qualquer momento.",
      "onb.q.lang": "1. Qual idioma voc\u00ea prefere?",
      "onb.lang.en.title": "English",
      "onb.lang.en.desc": "Content and interface in English (US formatting).",
      "onb.lang.pt.title": "Portugu\u00eas (Brasil)",
      "onb.lang.pt.desc": "Conte\u00fado e interface em portugu\u00eas, com formata\u00e7\u00e3o do Brasil.",
      "onb.lang.es.title": "Espa\u00f1ol (Latinoam\u00e9rica)",
      "onb.lang.es.desc": "Contenido e interfaz en espa\u00f1ol neutro, con formato latinoamericano.",
      "onb.q.role": "2. Qual \u00e9 a sua fun\u00e7\u00e3o?",
      "onb.role.csam.title": "CSAM",
      "onb.role.csam.desc": "Customer Success Account Manager. Exemplos e cen\u00e1rios assumem a vis\u00e3o do CSAM por padr\u00e3o.",
      "onb.role.csa.title": "CSA",
      "onb.role.csa.desc": "Cloud Solution Architect. Exemplos e cen\u00e1rios assumem a vis\u00e3o do CSA por padr\u00e3o.",
      "onb.role.customer.title": "Cliente",
      "onb.role.customer.desc": "O ponto de vista do cliente. Veja como a melhoria cont\u00ednua chega \u00e0 sua equipe \u2014 sem precisar vestir o chap\u00e9u de CSA ou CSAM.",
      "onb.role.practitioner.title": "Praticante de MC",
      "onb.role.practitioner.desc": "Um praticante geral de melhoria cont\u00ednua. Os exemplos focam em aplicar Lean Seis Sigma na sua pr\u00f3pria equipe, independente da fun\u00e7\u00e3o.",
      "onb.role.sss.title": "Services Solutions Seller",
      "onb.role.sss.desc": "Vender resultados de servi\u00e7os Microsoft. Os exemplos focam em qualificar, posicionar e fechar engajamentos ligados a valor mensur\u00e1vel.",
      "onb.role.sae.title": "Services Account Executive",
      "onb.role.sae.desc": "Dono da conta de servi\u00e7os. Os exemplos focam em planejamento de conta, stakeholders executivos, escopo, margem e renova\u00e7\u00f5es.",
      "onb.role.tas.title": "Technical Account Strategist",
      "onb.role.tas.desc": "O consultor t\u00e9cnico de confian\u00e7a. Os exemplos focam em sa\u00fade t\u00e9cnica, risco proativo e o roteiro de melhoria do cliente.",
      "onb.q.flow": "3. Como voc\u00ea gostaria de explorar?",
      "onb.flow.guided.title": "Caminho guiado",
      "onb.flow.guided.desc": "Uma \u00fanica progress\u00e3o, das ideias mais b\u00e1sicas \u00e0s mais avan\u00e7adas. Ideal se voc\u00ea \u00e9 novo em Lean Six Sigma.",
      "onb.flow.concept.title": "Navegar por conceito",
      "onb.flow.concept.desc": "M\u00f3dulos agrupados em categorias para voc\u00ea ir direto ao tema que precisar.",
      "onb.flow.belt.title": "Seguir uma faixa",
      "onb.flow.belt.desc": "Busque uma faixa de Lean Six Sigma. Escolha sua faixa-alvo e filtramos a biblioteca para o plano de aprendizado dela.",
      "onb.q.belt": "4. Qual faixa voc\u00ea est\u00e1 buscando?",
      "onb.start": "Come\u00e7ar a aprender",
      "onb.next": "Avan\u00e7ar",
      "onb.back": "Voltar",
      "onb.step": "Etapa {n} de {total}",
      "onb.aria": "Configure seu caminho",

      /* prefbar */
      "prefbar.showing": "Exibindo a vis\u00e3o",
      "prefbar.for": "para",
      "prefbar.flow.guided": "Caminho guiado",
      "prefbar.flow.concept": "Navegar por conceito",
      "prefbar.flow.beltSuffix": "plano",
      "prefbar.toggle.guided": "Caminho guiado",
      "prefbar.toggle.concept": "Por conceito",
      "prefbar.toggle.belt": "Por faixa",
      "prefbar.change": "Alterar idioma / fun\u00e7\u00e3o / caminho",
      "prefbar.targetBelt": "Faixa-alvo",
      "prefbar.aria.flow": "Escolher fluxo",
      "prefbar.aria.belt": "Escolher faixa-alvo",

      /* index listings */
      "index.modulesEach": "30 min cada",
      "index.module": "m\u00f3dulo", "index.modules": "m\u00f3dulos",
      "card.questionCheck": " quest\u00f5es de verifica\u00e7\u00e3o",
      "card.beltReq": "Conhecimento exigido para",
      "label.step": "PASSO", "label.module": "M\u00d3DULO",

      /* belt index */
      "belt.plan.eyebrow": "Plano de aprendizado da faixa",
      "belt.workingToward": "Avan\u00e7ando rumo \u00e0 sua",
      "belt.inThisPlan": "neste plano",
      "belt.cumulativeThrough": "cumulativo at\u00e9",
      "belt.ofStudy": "de estudo",
      "belt.yourTarget": "Sua meta",
      "belt.prerequisite": "Pr\u00e9-requisito",
      "belt.beyond": "Al\u00e9m da",
      "belt.moreModule": "m\u00f3dulo a mais", "belt.moreModules": "m\u00f3dulos a mais",
      "belt.cumulativeNote": "As faixas s\u00e3o cumulativas \u2014 escolher uma faixa superior mant\u00e9m tudo aqui e acrescenta o material mais aprofundado.",

      /* module page */
      "module.titleSuffix": "Smart CI Delivery",
      "module.delivery": "de entrega",
      "module.questionCheck": " quest\u00f5es de verifica\u00e7\u00e3o de conhecimento",
      "module.flow.guided": "Caminho guiado",
      "module.flow.concept": "Por conceito",
      "module.flow.beltSuffix": "plano",
      "module.posOf": "de",
      "module.beyondPlan": "al\u00e9m deste plano",
      "module.notFound": "M\u00f3dulo n\u00e3o encontrado. ",
      "module.returnAll": "Voltar a todos os m\u00f3dulos.",
      "sec.exec.kicker": "Resumo Executivo", "sec.exec.title": "Por que estes 30 minutos importam",
      "sec.gain.kicker": "O Que Voc\u00ea Vai Ganhar", "sec.gain.title": "O que voc\u00ea sair\u00e1 sabendo fazer",
      "sec.topic.kicker": "O Tema", "sec.topic.title": "O conceito, explicado",
      "sec.roles.kicker": "Exemplos por Fun\u00e7\u00e3o", "sec.roles.title": "Como isso aparece no campo",
      "sec.recap.kicker": "Recapitula\u00e7\u00e3o", "sec.recap.title": "Conceitos-chave & li\u00e7\u00f5es",
      "audio.kicker": "Áudio em formato de conversa",
      "audio.intro.title": "Ouça a cadência de melhoria PDCA de seis semanas",
      "audio.intro.description": "Prefere ouvir? Esta explicação em formato de conversa apresenta a cadência de melhoria de seis semanas do módulo e como um praticante de MC mantém o ciclo PDCA em movimento.",
      "audio.intro.meta": "5 min 15 s · áudio em inglês",
      "audio.intro.aria": "Explicação em formato de conversa sobre a cadência de melhoria PDCA de seis semanas",
      "audio.intro.link": "Ouvir o resumo em áudio",
      "audio.fallback": "Baixe a explicação em áudio.",
      "role.tab.csam": "CSAM \u2014 Customer Success Account Manager",
      "role.tab.csa": "CSA \u2014 Cloud Solution Architect",
      "role.tab.customer": "Cliente \u2014 o ponto de vista da sua equipe",
      "role.tab.practitioner": "Praticante de MC \u2014 melhoria cont\u00ednua na pr\u00e1tica",
      "role.tab.sss": "Services Solutions Seller \u2014 vendendo resultados de melhoria",
      "role.tab.sae": "Services Account Executive \u2014 dono da conta",
      "role.tab.tas": "Technical Account Strategist \u2014 o roteiro t\u00e9cnico",
      "role.panel.csam": "CSAM \u00b7 Customer Success Account Manager",
      "role.panel.csa": "CSA \u00b7 Cloud Solution Architect",
      "role.panel.customer": "Cliente \u00b7 o ponto de vista da sua equipe",
      "role.panel.practitioner": "Praticante de MC \u00b7 melhoria cont\u00ednua na pr\u00e1tica",
      "role.panel.sss": "Services Solutions Seller \u00b7 vendendo resultados de melhoria",
      "role.panel.sae": "Services Account Executive \u00b7 dono da conta",
      "role.panel.tas": "Technical Account Strategist \u00b7 o roteiro t\u00e9cnico",
      "role.short.customer": "Cliente",
      "role.short.practitioner": "Praticante de MC",
      "role.short.sss": "Services Solutions Seller",
      "role.short.sae": "Services Account Executive",
      "role.short.tas": "Technical Account Strategist",
      "module.prev": "\u2190 M\u00f3dulo anterior",
      "module.next": "Pr\u00f3ximo m\u00f3dulo \u2192",

      /* knowledge check */
      "kc.kicker": "Verifica\u00e7\u00e3o de Conhecimento",
      "kc.title": "Teste seu entendimento",
      "kc.intro": "Quest\u00f5es no estilo das certifica\u00e7\u00f5es da Microsoft. Confirme uma resposta para revelar a explica\u00e7\u00e3o.",
      "kc.questions": "Quest\u00f5es:", "kc.pass": "Aprova\u00e7\u00e3o:",
      "q.indexOf1": "Quest\u00e3o", "q.indexOf2": "de",
      "q.check": "Verificar resposta",
      "q.markerCorrect": "\u2713 Resposta correta",
      "q.markerYour": "\u2715 Sua resposta",
      "q.fb.correct": "Correto", "q.fb.notquite": "Quase l\u00e1",
      "kc.summary.pass": "Verifica\u00e7\u00e3o de conhecimento conclu\u00edda",
      "kc.summary.retry": "Quase l\u00e1",
      "kc.summary.passed": "Voc\u00ea foi aprovado. Revise os itens que errou.",
      "kc.summary.failedPrefix": "A nota de aprova\u00e7\u00e3o \u00e9",
      "kc.summary.failedSuffix": ". Revise o m\u00f3dulo e tente novamente.",
      "kc.retry": "Refazer verifica\u00e7\u00e3o",
      "kc.allModules": "Todos os m\u00f3dulos",

      /* points */
      "points.kicker": "Progresso",
      "points.title": "Seus pontos",
      "points.subtitle": "Cada m\u00f3dulo vale 100 pontos. Ao passar em uma verifica\u00e7\u00e3o de conhecimento, voc\u00ea ganha pontos proporcionais \u00e0 sua nota \u2014 80% rende 80 pontos.",
      "points.total": "Total de pontos",
      "points.byBelt": "Pontos por faixa",
      "points.modulesScored": "m\u00f3dulos pontuados",
      "points.modules": "m\u00f3dulos",
      "points.pts": "pts",
      "points.worth": "Vale",
      "points.newBest": "Novo recorde",
      "points.summary.earned": "Pontos ganhos",
      "points.empty": "Ainda sem pontos \u2014 passe em uma verifica\u00e7\u00e3o de conhecimento para come\u00e7ar a acumular pontos rumo \u00e0s suas faixas.",
      "points.reset": "Zerar pontos",
      "points.reset.confirm": "Zerar todos os pontos ganhos? Isso n\u00e3o pode ser desfeito.",

      /* exam start */
      "exam.hero.eyebrow": "Avalia\u00e7\u00e3o pr\u00e1tica no estilo das certifica\u00e7\u00f5es da Microsoft",
      "exam.hero.lede": "Uma avalia\u00e7\u00e3o realista, no estilo de exame, sobre toda a biblioteca Smart CI. Escolha o modo Pr\u00e1tica para aprender com feedback imediato, ou o modo Certifica\u00e7\u00e3o para uma tentativa cronometrada e pontuada que espelha a experi\u00eancia real de exame.",
      "exam.fact.bank": "quest\u00f5es no banco",
      "exam.fact.perAttempt": "por tentativa de certifica\u00e7\u00e3o",
      "exam.fact.timeLimit": "limite de tempo (modo cert.)",
      "exam.fact.scoreToPass": "pontua\u00e7\u00e3o para aprova\u00e7\u00e3o",
      "exam.q.short": "Q", "exam.min": "min",
      "exam.practice.badge": "Modo Pr\u00e1tica / Prepara\u00e7\u00e3o",
      "exam.practice.title": "Aprenda com feedback imediato",
      "exam.practice.desc": "Uma quest\u00e3o por vez. Confirme uma resposta e a alternativa correta e a explica\u00e7\u00e3o completa aparecem imediatamente. Sem cron\u00f4metro \u2014 ideal para construir conhecimento antes de uma tentativa cronometrada.",
      "exam.practice.li1": "Resposta + justificativa imediatas a cada item",
      "exam.practice.li2": "Foque em uma \u00fanica \u00e1rea de compet\u00eancia ou em todo o banco",
      "exam.practice.li3": "Sem cron\u00f4metro, refa\u00e7a quantas vezes quiser",
      "exam.practice.start": "Iniciar pr\u00e1tica",
      "exam.field.length": "Tamanho", "exam.field.skill": "\u00c1rea de compet\u00eancia",
      "exam.len.questions": "quest\u00f5es",
      "exam.len.all": "Todas as", "exam.len.allSuffix": "quest\u00f5es",
      "exam.skill.all": "Todas as \u00e1reas",
      "exam.cap.msg": "A \u00e1rea de compet\u00eancia \u201c{skill}\u201d tem apenas {avail} quest\u00e3o(\u00f5es) dispon\u00edvel(eis) \u2014 menos do que as {req} que voc\u00ea selecionou. Iniciar com o m\u00e1ximo de {avail} dispon\u00edvel(eis)?",
      "exam.cert.badge": "Modo Certifica\u00e7\u00e3o",
      "exam.cert.title": "Cronometrado, pontuado, realista",
      "exam.cert.start": "Iniciar exame de certifica\u00e7\u00e3o",      "exam.name": "Fundamentos de Melhoria Cont\u00ednua",
      "exam.cert.desc": "{len} quest\u00f5es em {min} minutos. Sem feedback at\u00e9 que voc\u00ea envie. Marque itens para revis\u00e3o, revisite-os a partir de uma tela de revis\u00e3o e receba uma pontua\u00e7\u00e3o em escala e um detalhamento por \u00e1rea de compet\u00eancia \u2014 exatamente como um exame de certifica\u00e7\u00e3o da Microsoft.",
      "exam.cert.li1": "{len} quest\u00f5es \u00b7 contagem regressiva de {min} minutos",
      "exam.cert.li3": "Pontua\u00e7\u00e3o em escala de at\u00e9 {max} \u00b7 aprova\u00e7\u00e3o em {pass}",      "exam.cert.markLi": "Marcar para revis\u00e3o + grade de revis\u00e3o ao final",
      "exam.cert.reportLi": "Relat\u00f3rio de desempenho por \u00e1rea de compet\u00eancia",
      "exam.skills.title": "Compet\u00eancias avaliadas",
      "exam.skills.note": "Uma tentativa de certifica\u00e7\u00e3o seleciona quest\u00f5es entre estas \u00e1reas de compet\u00eancia usando os pesos indicados.",
      "exam.skills.col.area": "\u00c1rea de compet\u00eancia", "exam.skills.col.weight": "Peso", "exam.skills.col.bank": "Banco",
      "exam.disclaimer": "Esta \u00e9 uma avalia\u00e7\u00e3o pr\u00e1tica n\u00e3o oficial e interna, constru\u00edda a partir da base de conhecimento Smart CI para imitar o formato dos exames de certifica\u00e7\u00e3o da Microsoft. O CI-900 \u00e9, neste momento, um conceito proposto e somente interno, para p\u00fablico interno apenas. N\u00e3o \u00e9 afiliado nem endossado pela Microsoft e n\u00e3o \u00e9 um exame ou certifica\u00e7\u00e3o real da Microsoft.",

      /* exam session */
      "exam.mode.cert": "Modo Certifica\u00e7\u00e3o", "exam.mode.practice": "Modo Pr\u00e1tica",
      "exam.bar.question": "Quest\u00e3o", "exam.bar.of": "de", "exam.bar.answered": "respondidas",
      "exam.endPractice": "Encerrar pr\u00e1tica",
      "exam.question": "Quest\u00e3o",
      "exam.chooseBest": "Escolha a melhor resposta.",
      "exam.prev": "\u2190 Anterior", "exam.next": "Pr\u00f3xima \u2192",
      "exam.markReview": "Marcar para revis\u00e3o",
      "exam.review.btn": "Revis\u00e3o \u2630",
      "exam.reviewSubmit": "Revisar & enviar", "exam.finish": "Concluir",
      "exam.reviewScreen": "Tela de revis\u00e3o",
      "exam.review.title": "Revise suas respostas",
      "exam.review.note": "Selecione qualquer quest\u00e3o para retornar a ela. Os itens sinalizados ficam marcados. Quest\u00f5es n\u00e3o respondidas s\u00e3o pontuadas como incorretas.",
      "exam.legend.answered": "Respondida", "exam.legend.unanswered": "N\u00e3o respondida", "exam.legend.marked": "Marcada para revis\u00e3o",
      "exam.allAnswered": "Todas as quest\u00f5es respondidas.",
      "exam.stillUnanswered1": "quest\u00e3o ainda sem resposta.", "exam.stillUnanswered2": "quest\u00f5es ainda sem resposta.",
      "exam.markedForReview": "marcadas para revis\u00e3o.",
      "exam.returnQuestions": "\u2190 Voltar \u00e0s quest\u00f5es",
      "exam.submit": "Enviar exame",
      "exam.confirm.unanswered1": "Voc\u00ea tem", "exam.confirm.unanswered2": "quest\u00e3o sem resposta",
      "exam.confirm.unanswered2p": "quest\u00f5es sem resposta",
      "exam.confirm.anyway": ". Enviar mesmo assim? Itens sem resposta s\u00e3o pontuados como incorretos.",
      "exam.confirm.submit": "Enviar seu exame para pontua\u00e7\u00e3o?",
      "exam.confirm.endPractice": "Encerrar esta sess\u00e3o de pr\u00e1tica e ver seus resultados?",

      /* exam report */
      "exam.attempt": "Tentativa de certifica\u00e7\u00e3o", "exam.session": "Sess\u00e3o de pr\u00e1tica",
      "exam.pass": "APROVADO", "exam.fail": "N\u00c3O APROVADO",
      "exam.passingScore": "Nota de aprova\u00e7\u00e3o:",
      "exam.passLine": "aprova\u00e7\u00e3o",
      "exam.correctSuffix": "corretas",
      "exam.ofCorrect": "corretas \u00b7 tempo usado",
      "exam.timeExpired": "Tempo esgotado \u00b7",
      "exam.attemptedOn": "Realizado em",
      "exam.breakdown.title": "Desempenho por \u00e1rea de compet\u00eancia",
      "exam.answers.review": "Revisar todas as quest\u00f5es & explica\u00e7\u00f5es",
      "exam.answers.hide": "Ocultar revis\u00e3o das quest\u00f5es",
      "exam.retakeCert": "Refazer exame de certifica\u00e7\u00e3o", "exam.newPractice": "Nova sess\u00e3o de pr\u00e1tica",
      "exam.backModules": "Voltar aos m\u00f3dulos",
      "exam.answer.correct": "Correta", "exam.answer.incorrect": "Incorreta", "exam.answer.unanswered": "Sem resposta",
      "exam.answer.markCorrect": " \u2713 Resposta correta", "exam.answer.markYour": " \u2715 Sua resposta", "exam.answer.markYourCorrect": " \u2713 Sua resposta",
      "exam.answer.explanation": "Explica\u00e7\u00e3o:",
      "exam.noQuestions": "Nenhuma quest\u00e3o dispon\u00edvel.",

      /* group / stage / belt display names */
      "group.Foundations": "Fundamentos",
      "group.Methodologies & Cycles": "Metodologias & Ciclos",
      "group.Value & Quality Definition": "Defini\u00e7\u00e3o de Valor & Qualidade",
      "group.Process Mapping & Analysis": "Mapeamento & An\u00e1lise de Processos",
      "group.Workplace, Flow & Standardization": "Ambiente, Fluxo & Padroniza\u00e7\u00e3o",
      "group.Measurement & Control": "Medi\u00e7\u00e3o & Controle",
      "group.Strategy & Governance": "Estrat\u00e9gia & Governan\u00e7a",

      "stage.1": "Etapa 1 \u00b7 Comece Aqui \u2014 O Que \u00e9 MC",
      "stage.2": "Etapa 2 \u00b7 Enxergar Valor e Desperd\u00edcio",
      "stage.3": "Etapa 3 \u00b7 Organizar e Padronizar",
      "stage.4": "Etapa 4 \u00b7 Melhorar em Ciclos",
      "stage.5": "Etapa 5 \u00b7 Mapear e Analisar o Processo",
      "stage.6": "Etapa 6 \u00b7 Encontrar a Causa Raiz",
      "stage.7": "Etapa 7 \u00b7 Equilibrar o Fluxo",
      "stage.8": "Etapa 8 \u00b7 Medir com Dados",
      "stage.9": "Etapa 9 \u00b7 Comprovar Estatisticamente",
      "stage.10": "Etapa 10 \u00b7 Liderar e Governar",

      "belt.white.name": "Faixa Branca", "belt.white.tagline": "Consci\u00eancia & vocabul\u00e1rio",
      "belt.white.goal": "Conhe\u00e7a a linguagem da melhoria cont\u00ednua e reconhe\u00e7a as ferramentas centrais \u2014 voc\u00ea entende o que s\u00e3o e por que importam, mesmo antes de aplic\u00e1-las.",
      "belt.yellow.name": "Faixa Amarela", "belt.yellow.tagline": "Praticante \u2014 contribui com melhorias",
      "belt.yellow.goal": "Participe de eventos de melhoria: conduza os 5 Porqu\u00eas em um problema confirmado, contribua com um Ishikawa e apoie o trabalho padronizado e a prova de erros.",
      "belt.green.name": "Faixa Verde", "belt.green.tagline": "Lidera projetos de pequeno a m\u00e9dio porte",
      "belt.green.goal": "Conduza projetos DMAIC de ponta a ponta com mapeamento de processos, balanceamento de fluxo e estat\u00edstica b\u00e1sica.",
      "belt.black.name": "Faixa Preta", "belt.black.tagline": "Lidera programas, mentora & governa",
      "belt.black.goal": "Lidere programas multifuncionais com estat\u00edstica avan\u00e7ada, an\u00e1lise de risco e estrat\u00e9gia de MC \u2014 e mentore Faixas Verdes.",
      "belt.hoursSuffix": "horas",

      "domain.foundations": "Descrever fundamentos e conceitos da melhoria cont\u00ednua",
      "domain.methods": "Aplicar metodologias e ciclos de melhoria",
      "domain.value": "Definir valor e qualidade para o cliente",
      "domain.mapping": "Mapear e analisar processos e causas raiz",
      "domain.flow": "Otimizar ambiente, fluxo e padroniza\u00e7\u00e3o",
      "domain.measure": "Medir e controlar processos estatisticamente",
      "domain.govern": "Liderar estrat\u00e9gia e governan\u00e7a de MC",

      /* feedback (Voice of Customer) */
      "voc.button": "Coment\u00e1rios",
      "voc.aria": "Envie seu feedback",
      "voc.title": "Envie seu feedback",
      "voc.lede": "Ajude-nos a melhorar a S\u00e9rie de Entregas de 30 Minutos. Seu feedback \u00e9 coletado como uma issue de Voz do Cliente (VOC) no reposit\u00f3rio GitHub do projeto.",
      "voc.github.note": "Ao enviar, abrimos uma issue do GitHub j\u00e1 preenchida em uma nova aba &mdash; revise e clique em <strong>Submit new issue</strong> para enviar. \u00c9 necess\u00e1rio ter uma conta do GitHub com acesso ao reposit\u00f3rio.",
      "voc.type.label": "Que tipo de feedback \u00e9 este?",
      "voc.type.content": "Precis\u00e3o do conte\u00fado",
      "voc.type.suggestion": "Sugest\u00e3o ou melhoria",
      "voc.type.bug": "Erro ou link quebrado",
      "voc.type.question": "D\u00favida",
      "voc.type.praise": "Elogio",
      "voc.type.other": "Outro",
      "voc.rating.label": "Avalia\u00e7\u00e3o geral (opcional)",
      "voc.rating.clear": "Limpar avalia\u00e7\u00e3o",
      "voc.subject.label": "Resumo",
      "voc.subject.ph": "Um t\u00edtulo curto para seu feedback",
      "voc.details.label": "Detalhes",
      "voc.details.ph": "O que funcionou, o que n\u00e3o funcionou e suas sugest\u00f5es\u2026",
      "voc.name.label": "Seu nome (opcional)",
      "voc.name.ph": "Para retornarmos, se necess\u00e1rio",
      "voc.required": "Adicione um resumo e alguns detalhes antes de enviar.",
      "voc.submit": "Abrir issue no GitHub",
      "voc.cancel": "Cancelar",
      "survey.exam.eyebrow": "Pesquisa r\u00e1pida",
      "survey.exam.title": "Como foi esta avalia\u00e7\u00e3o?",
      "survey.exam.lede": "Algumas perguntas r\u00e1pidas nos ajudam a melhorar o exame pr\u00e1tico CI-900.",
      "survey.exam.q.label": "Como foi o n\u00edvel de dificuldade?",
      "survey.exam.q.easy": "F\u00e1cil demais",
      "survey.exam.q.right": "No ponto certo",
      "survey.exam.q.hard": "Dif\u00edcil demais",
      "survey.belt.eyebrow": "Faixa conclu\u00edda \u00b7 Pesquisa r\u00e1pida",
      "survey.belt.title": "Voc\u00ea chegou ao fim do plano {belt}",
      "survey.belt.lede": "Parab\u00e9ns! Conte como esta faixa funcionou para voc\u00ea para que possamos melhor\u00e1-la.",
      "survey.belt.q.label": "Qu\u00e3o confiante voc\u00ea se sente para aplicar estas ferramentas?",
      "survey.belt.q.low": "Ainda n\u00e3o confiante",
      "survey.belt.q.mid": "Chegando l\u00e1",
      "survey.belt.q.high": "Confiante",
      "survey.rating.label": "De modo geral, que nota voc\u00ea daria?",
      "survey.comment.label": "Algo a acrescentar? (opcional)",
      "survey.comment.ph": "O que funcionou, o que n\u00e3o funcionou e quaisquer sugest\u00f5es\u2026",
      "survey.github.note": "Ao enviar, abre-se uma issue do GitHub pr\u00e9-preenchida em uma nova aba &mdash; revise-a e clique em <strong>Submit new issue</strong> para enviar. \u00c9 necess\u00e1ria uma conta do GitHub com acesso ao reposit\u00f3rio.",
      "survey.required": "Adicione uma avalia\u00e7\u00e3o geral antes de enviar.",
      "survey.submit": "Enviar pesquisa",
      "survey.dismiss": "Agora n\u00e3o",
      "survey.thanks.title": "Obrigado!",
      "survey.thanks.body": "Seu retorno nos ajuda a melhorar a S\u00e9rie de Entregas de 30 Minutos."
    },

    "es-419": {
      "telemetry.aria": "Preferencia de datos de uso",
      "telemetry.message": "Permite recopilar datos de uso anónimos para ayudarnos a mejorar esta experiencia de aprendizaje. No se recopilan nombres, respuestas ni texto de comentarios.",
      "telemetry.deny": "Ahora no",
      "telemetry.allow": "Permitir",

      /* shared chrome */
      "internal.notice": "<strong>Interno y propuesto &mdash; no es una oferta oficial de Microsoft.</strong> &ldquo;CI-900&rdquo; y esta serie de entrega son, por ahora, una propuesta interna dirigida \u00fanicamente a una audiencia interna. No son un producto, certificaci\u00f3n ni examen de Microsoft, y no est\u00e1n afiliados, avalados ni patrocinados por Microsoft. No los compartas externamente.",
      "internal.notice.exam": "<strong>Interno y propuesto &mdash; no es una oferta oficial de Microsoft.</strong> &ldquo;CI-900&rdquo; es, por ahora, una propuesta interna dirigida \u00fanicamente a una audiencia interna. No es una certificaci\u00f3n ni examen de Microsoft y no est\u00e1 afiliado, avalado ni patrocinado por Microsoft. No lo compartas externamente.",
      "breadcrumb.series": "Smart CI \u2014 Serie de Entregas de 30 Minutos",
      "breadcrumb.module": "M\u00f3dulo",
      "breadcrumb.exam": "Examen de Pr\u00e1ctica CI-900",
      "footer.index": "Smart CI Tools \u00b7 Serie de Entregas de 30 Minutos \u00b7 Interno y propuesto \u2014 no es una oferta oficial de Microsoft \u00b7 Construido a partir de la base de conocimiento CI for CI",
      "footer.module": "Smart CI Tools \u00b7 Serie de Entregas de 30 Minutos",
      "footer.exam": "Smart CI Tools \u00b7 Examen de Pr\u00e1ctica CI-900 \u00b7 Concepto propuesto y solo interno \u2014 no es una oferta oficial de Microsoft \u00b7 Evaluaci\u00f3n de pr\u00e1ctica no oficial construida a partir de la base de conocimiento CI for CI",

      /* index hero */
      "index.title": "Smart CI \u2014 Serie de Entregas de 30 Minutos",
      "hero.eyebrow": "CI \u00b7 in \u00b7 30",
      "hero.title": "Mejora Continua \u2014 Serie de Entregas de 30 Minutos",
      "hero.lede": "Todos los temas de Lean Six Sigma de la biblioteca Smart CI, reempaquetados en sesiones concisas de 30 minutos. Elige tu rol y selecciona un camino &mdash; una <strong>progresi\u00f3n guiada</strong> desde los conceptos m\u00e1s b\u00e1sicos hasta los m\u00e1s avanzados, <strong>navega por concepto</strong> y categor\u00eda, o <strong>sigue un cintur\u00f3n</strong> para filtrar la biblioteca seg\u00fan el plan de aprendizaje del cintur\u00f3n de Lean Six Sigma que persigues. Cada m\u00f3dulo abre con un resumen ejecutivo, describe lo que obtendr\u00e1s en lenguaje sencillo, explica el concepto, muestra ejemplos por rol para CSAM y CSA, recapitula los puntos clave y cierra con una verificaci\u00f3n de conocimiento al estilo de las certificaciones de Microsoft.",
      "hero.stat.modules": "m\u00f3dulos de 30 min",
      "hero.stat.roles": "roles: CSAM &amp; CSA",
      "hero.stat.parts": "partes por m\u00f3dulo",
      "hero.stat.questions": "preguntas de verificaci\u00f3n",

      /* format section */
      "format.heading": "C\u00f3mo se estructura cada m\u00f3dulo de 30 minutos",
      "format.part1.label": "Resumen Ejecutivo", "format.part1.desc": "Por qu\u00e9 importa la sesi\u00f3n, para l\u00edderes.",
      "format.part2.label": "Lo Que Obtendr\u00e1s", "format.part2.desc": "Resultados en lenguaje sencillo.",
      "format.part3.label": "El Tema", "format.part3.desc": "El concepto, explicado.",
      "format.part4.label": "Ejemplos por Rol", "format.part4.desc": "Escenarios de CSAM &amp; CSA.",
      "format.part5.label": "Recapitulaci\u00f3n", "format.part5.desc": "Conceptos clave &amp; aprendizajes.",
      "format.part6.label": "Verificaci\u00f3n de Conocimiento", "format.part6.desc": "Cuestionario estilo cert. MS.",
      "format.part": "PARTE",

      /* exam CTA on index */
      "examcta.eyebrow": "Pon a prueba tu preparaci\u00f3n",
      "examcta.title": "CI-900: Fundamentos de la Mejora Continua",
      "examcta.desc": "Un examen de pr\u00e1ctica al <em>estilo</em> de una certificaci\u00f3n de Microsoft, sobre toda la biblioteca. Usa el <strong>modo Pr\u00e1ctica</strong> para aprender con retroalimentaci\u00f3n inmediata, o el <strong>modo Certificaci\u00f3n</strong> para un intento cronometrado con puntaje escalado, pantalla de marcado para revisi\u00f3n e informe por \u00e1rea de competencia. <strong>CI-900 es un concepto propuesto y solo interno &mdash; no es una certificaci\u00f3n ni examen real de Microsoft.</strong>",
      "examcta.btn": "Realizar el examen de pr\u00e1ctica \u2192",

      /* onboarding */
      "onb.eyebrow": "Smart CI \u00b7 Configura tu camino",
      "onb.title": "Bienvenido(a) \u2014 personalicemos esto para ti",
      "onb.lede": "Elige tu idioma, tu rol y c\u00f3mo prefieres recorrer el material. Puedes cambiar los tres en cualquier momento.",
      "onb.q.lang": "1. \u00bfQu\u00e9 idioma prefieres?",
      "onb.lang.en.title": "English",
      "onb.lang.en.desc": "Content and interface in English (US formatting).",
      "onb.lang.pt.title": "Portugu\u00eas (Brasil)",
      "onb.lang.pt.desc": "Conte\u00fado e interface em portugu\u00eas, com formata\u00e7\u00e3o do Brasil.",
      "onb.lang.es.title": "Espa\u00f1ol (Latinoam\u00e9rica)",
      "onb.lang.es.desc": "Contenido e interfaz en espa\u00f1ol neutro, con formato latinoamericano.",
      "onb.q.role": "2. \u00bfCu\u00e1l es tu rol?",
      "onb.role.csam.title": "CSAM",
      "onb.role.csam.desc": "Customer Success Account Manager. Los ejemplos y escenarios toman la vista del CSAM por defecto.",
      "onb.role.csa.title": "CSA",
      "onb.role.csa.desc": "Cloud Solution Architect. Los ejemplos y escenarios toman la vista del CSA por defecto.",
      "onb.role.customer.title": "Cliente",
      "onb.role.customer.desc": "El punto de vista del cliente. Mira c\u00f3mo la mejora continua impacta a tu equipo \u2014 sin necesidad de ponerte el sombrero de CSA o CSAM.",
      "onb.role.practitioner.title": "Practicante de MC",
      "onb.role.practitioner.desc": "Un practicante general de mejora continua. Los ejemplos se centran en aplicar Lean Seis Sigma en tu propio equipo, sin importar el rol.",
      "onb.role.sss.title": "Services Solutions Seller",
      "onb.role.sss.desc": "Vender resultados de servicios de Microsoft. Los ejemplos se centran en calificar, posicionar y cerrar compromisos ligados a valor medible.",
      "onb.role.sae.title": "Services Account Executive",
      "onb.role.sae.desc": "Due\u00f1o de la cuenta de servicios. Los ejemplos se centran en planificaci\u00f3n de cuenta, stakeholders ejecutivos, alcance, margen y renovaciones.",
      "onb.role.tas.title": "Technical Account Strategist",
      "onb.role.tas.desc": "El asesor t\u00e9cnico de confianza. Los ejemplos se centran en la salud t\u00e9cnica, el riesgo proactivo y la hoja de ruta de mejora del cliente.",
      "onb.q.flow": "3. \u00bfC\u00f3mo te gustar\u00eda explorar?",
      "onb.flow.guided.title": "Camino guiado",
      "onb.flow.guided.desc": "Una sola progresi\u00f3n, desde las ideas m\u00e1s b\u00e1sicas hasta las m\u00e1s avanzadas. Ideal si eres nuevo en Lean Six Sigma.",
      "onb.flow.concept.title": "Navegar por concepto",
      "onb.flow.concept.desc": "M\u00f3dulos agrupados en categor\u00edas para que vayas directo al tema que necesites.",
      "onb.flow.belt.title": "Seguir un cintur\u00f3n",
      "onb.flow.belt.desc": "Persigue un cintur\u00f3n de Lean Six Sigma. Elige tu cintur\u00f3n objetivo y filtramos la biblioteca seg\u00fan su plan de aprendizaje.",
      "onb.q.belt": "4. \u00bfQu\u00e9 cintur\u00f3n persigues?",
      "onb.start": "Comenzar a aprender",
      "onb.next": "Siguiente",
      "onb.back": "Atr\u00e1s",
      "onb.step": "Paso {n} de {total}",
      "onb.aria": "Configura tu camino",

      /* prefbar */
      "prefbar.showing": "Mostrando la vista",
      "prefbar.for": "para",
      "prefbar.flow.guided": "Camino guiado",
      "prefbar.flow.concept": "Navegar por concepto",
      "prefbar.flow.beltSuffix": "plan",
      "prefbar.toggle.guided": "Camino guiado",
      "prefbar.toggle.concept": "Por concepto",
      "prefbar.toggle.belt": "Por cintur\u00f3n",
      "prefbar.change": "Cambiar idioma / rol / camino",
      "prefbar.targetBelt": "Cintur\u00f3n objetivo",
      "prefbar.aria.flow": "Elegir flujo",
      "prefbar.aria.belt": "Elegir cintur\u00f3n objetivo",

      /* index listings */
      "index.modulesEach": "30 min cada uno",
      "index.module": "m\u00f3dulo", "index.modules": "m\u00f3dulos",
      "card.questionCheck": " preguntas de verificaci\u00f3n",
      "card.beltReq": "Conocimiento requerido para",
      "label.step": "PASO", "label.module": "M\u00d3DULO",

      /* belt index */
      "belt.plan.eyebrow": "Plan de aprendizaje del cintur\u00f3n",
      "belt.workingToward": "Avanzando hacia tu",
      "belt.inThisPlan": "en este plan",
      "belt.cumulativeThrough": "acumulado hasta",
      "belt.ofStudy": "de estudio",
      "belt.yourTarget": "Tu meta",
      "belt.prerequisite": "Prerrequisito",
      "belt.beyond": "M\u00e1s all\u00e1 del",
      "belt.moreModule": "m\u00f3dulo m\u00e1s", "belt.moreModules": "m\u00f3dulos m\u00e1s",
      "belt.cumulativeNote": "Los cinturones son acumulativos \u2014 elegir un cintur\u00f3n superior conserva todo lo de aqu\u00ed y agrega el material m\u00e1s profundo.",

      /* module page */
      "module.titleSuffix": "Smart CI Delivery",
      "module.delivery": "de entrega",
      "module.questionCheck": " preguntas de verificaci\u00f3n de conocimiento",
      "module.flow.guided": "Camino guiado",
      "module.flow.concept": "Por concepto",
      "module.flow.beltSuffix": "plan",
      "module.posOf": "de",
      "module.beyondPlan": "m\u00e1s all\u00e1 de este plan",
      "module.notFound": "M\u00f3dulo no encontrado. ",
      "module.returnAll": "Volver a todos los m\u00f3dulos.",
      "sec.exec.kicker": "Resumen Ejecutivo", "sec.exec.title": "Por qu\u00e9 importan estos 30 minutos",
      "sec.gain.kicker": "Lo Que Obtendr\u00e1s", "sec.gain.title": "Lo que te llevar\u00e1s y podr\u00e1s hacer",
      "sec.topic.kicker": "El Tema", "sec.topic.title": "El concepto, explicado",
      "sec.roles.kicker": "Ejemplos por Rol", "sec.roles.title": "C\u00f3mo se ve en el terreno",
      "sec.recap.kicker": "Recapitulaci\u00f3n", "sec.recap.title": "Conceptos clave & aprendizajes",
      "audio.kicker": "Audio conversacional",
      "audio.intro.title": "Escucha la cadencia de mejora PDCA de seis semanas",
      "audio.intro.description": "¿Prefieres escuchar? Esta explicación conversacional presenta la cadencia de mejora de seis semanas del módulo y cómo un practicante de MC mantiene el ciclo PDCA en movimiento.",
      "audio.intro.meta": "5 min 15 s · audio en inglés",
      "audio.intro.aria": "Explicación conversacional de la cadencia de mejora PDCA de seis semanas",
      "audio.intro.link": "Escuchar el resumen de audio",
      "audio.fallback": "Descarga la explicación en audio.",
      "role.tab.csam": "CSAM \u2014 Customer Success Account Manager",
      "role.tab.csa": "CSA \u2014 Cloud Solution Architect",
      "role.tab.customer": "Cliente \u2014 el punto de vista de tu equipo",
      "role.tab.practitioner": "Practicante de MC \u2014 la mejora continua en la pr\u00e1ctica",
      "role.tab.sss": "Services Solutions Seller \u2014 vendiendo resultados de mejora",
      "role.tab.sae": "Services Account Executive \u2014 due\u00f1o de la cuenta",
      "role.tab.tas": "Technical Account Strategist \u2014 la hoja de ruta t\u00e9cnica",
      "role.panel.csam": "CSAM \u00b7 Customer Success Account Manager",
      "role.panel.csa": "CSA \u00b7 Cloud Solution Architect",
      "role.panel.customer": "Cliente \u00b7 el punto de vista de tu equipo",
      "role.panel.practitioner": "Practicante de MC \u00b7 la mejora continua en la pr\u00e1ctica",
      "role.panel.sss": "Services Solutions Seller \u00b7 vendiendo resultados de mejora",
      "role.panel.sae": "Services Account Executive \u00b7 due\u00f1o de la cuenta",
      "role.panel.tas": "Technical Account Strategist \u00b7 la hoja de ruta t\u00e9cnica",
      "role.short.customer": "Cliente",
      "role.short.practitioner": "Practicante de MC",
      "role.short.sss": "Services Solutions Seller",
      "role.short.sae": "Services Account Executive",
      "role.short.tas": "Technical Account Strategist",
      "module.prev": "\u2190 M\u00f3dulo anterior",
      "module.next": "M\u00f3dulo siguiente \u2192",

      /* knowledge check */
      "kc.kicker": "Verificaci\u00f3n de Conocimiento",
      "kc.title": "Pon a prueba tu comprensi\u00f3n",
      "kc.intro": "Preguntas al estilo de las certificaciones de Microsoft. Confirma una respuesta para revelar la explicaci\u00f3n.",
      "kc.questions": "Preguntas:", "kc.pass": "Aprobaci\u00f3n:",
      "q.indexOf1": "Pregunta", "q.indexOf2": "de",
      "q.check": "Verificar respuesta",
      "q.markerCorrect": "\u2713 Respuesta correcta",
      "q.markerYour": "\u2715 Tu respuesta",
      "q.fb.correct": "Correcto", "q.fb.notquite": "Casi",
      "kc.summary.pass": "Verificaci\u00f3n de conocimiento completada",
      "kc.summary.retry": "Casi lo logras",
      "kc.summary.passed": "Aprobaste. Revisa los \u00edtems que fallaste.",
      "kc.summary.failedPrefix": "El puntaje de aprobaci\u00f3n es",
      "kc.summary.failedSuffix": ". Repasa el m\u00f3dulo e int\u00e9ntalo de nuevo.",
      "kc.retry": "Reintentar verificaci\u00f3n",
      "kc.allModules": "Todos los m\u00f3dulos",

      /* points */
      "points.kicker": "Progreso",
      "points.title": "Tus puntos",
      "points.subtitle": "Cada m\u00f3dulo vale 100 puntos. Al aprobar una verificaci\u00f3n de conocimientos, ganas puntos en proporci\u00f3n a tu resultado \u2014 80% otorga 80 puntos.",
      "points.total": "Puntos totales",
      "points.byBelt": "Puntos por cintur\u00f3n",
      "points.modulesScored": "m\u00f3dulos puntuados",
      "points.modules": "m\u00f3dulos",
      "points.pts": "pts",
      "points.worth": "Vale",
      "points.newBest": "Nuevo r\u00e9cord",
      "points.summary.earned": "Puntos ganados",
      "points.empty": "A\u00fan sin puntos \u2014 aprueba una verificaci\u00f3n de conocimientos para empezar a acumular puntos hacia tus cinturones.",
      "points.reset": "Restablecer puntos",
      "points.reset.confirm": "\u00bfRestablecer todos los puntos ganados? Esto no se puede deshacer.",

      /* exam start */
      "exam.hero.eyebrow": "Evaluaci\u00f3n de pr\u00e1ctica al estilo de las certificaciones de Microsoft",
      "exam.hero.lede": "Una evaluaci\u00f3n realista, al estilo de examen, sobre toda la biblioteca Smart CI. Elige el modo Pr\u00e1ctica para aprender con retroalimentaci\u00f3n inmediata, o el modo Certificaci\u00f3n para un intento cronometrado y puntuado que refleja la experiencia real de examen.",
      "exam.fact.bank": "preguntas en el banco",
      "exam.fact.perAttempt": "por intento de certificaci\u00f3n",
      "exam.fact.timeLimit": "l\u00edmite de tiempo (modo cert.)",
      "exam.fact.scoreToPass": "puntaje para aprobar",
      "exam.q.short": "P", "exam.min": "min",
      "exam.practice.badge": "Modo Pr\u00e1ctica / Preparaci\u00f3n",
      "exam.practice.title": "Aprende con retroalimentaci\u00f3n inmediata",
      "exam.practice.desc": "Una pregunta a la vez. Confirma una respuesta y la opci\u00f3n correcta y la explicaci\u00f3n completa aparecen de inmediato. Sin cron\u00f3metro \u2014 ideal para construir conocimiento antes de un intento cronometrado.",
      "exam.practice.li1": "Respuesta + justificaci\u00f3n inmediatas en cada \u00edtem",
      "exam.practice.li2": "Enf\u00f3cate en una sola \u00e1rea de competencia o en todo el banco",
      "exam.practice.li3": "Sin cron\u00f3metro, repite cuantas veces quieras",
      "exam.practice.start": "Iniciar pr\u00e1ctica",
      "exam.field.length": "Cantidad", "exam.field.skill": "\u00c1rea de competencia",
      "exam.len.questions": "preguntas",
      "exam.len.all": "Todas las", "exam.len.allSuffix": "preguntas",
      "exam.skill.all": "Todas las \u00e1reas",
      "exam.cap.msg": "El \u00e1rea de competencia \u201c{skill}\u201d tiene solo {avail} pregunta(s) disponible(s) \u2014 menos que las {req} que seleccionaste. \u00bfIniciar con el m\u00e1ximo de {avail} disponible(s)?",
      "exam.cert.badge": "Modo Certificaci\u00f3n",
      "exam.cert.title": "Cronometrado, puntuado, realista",
      "exam.cert.start": "Iniciar examen de certificaci\u00f3n",
      "exam.name": "Fundamentos de la Mejora Continua",
      "exam.cert.desc": "{len} preguntas en {min} minutos. Sin retroalimentaci\u00f3n hasta que env\u00edes. Marca \u00edtems para revisi\u00f3n, vu\u00e9lvelos a ver desde una pantalla de revisi\u00f3n y recibe un puntaje escalado y un desglose por \u00e1rea de competencia \u2014 exactamente como un examen de certificaci\u00f3n de Microsoft.",
      "exam.cert.li1": "{len} preguntas \u00b7 cuenta regresiva de {min} minutos",
      "exam.cert.li3": "Puntaje escalado de hasta {max} \u00b7 aprobaci\u00f3n en {pass}",
      "exam.cert.markLi": "Marcar para revisi\u00f3n + cuadr\u00edcula de revisi\u00f3n al final",
      "exam.cert.reportLi": "Informe de desempe\u00f1o por \u00e1rea de competencia",
      "exam.skills.title": "Competencias evaluadas",
      "exam.skills.note": "Un intento de certificaci\u00f3n toma preguntas de estas \u00e1reas de competencia usando las ponderaciones indicadas.",
      "exam.skills.col.area": "\u00c1rea de competencia", "exam.skills.col.weight": "Ponderaci\u00f3n", "exam.skills.col.bank": "Banco",
      "exam.disclaimer": "Esta es una evaluaci\u00f3n de pr\u00e1ctica no oficial e interna, construida a partir de la base de conocimiento Smart CI para imitar el formato de los ex\u00e1menes de certificaci\u00f3n de Microsoft. CI-900 es, por ahora, un concepto propuesto y solo interno, para audiencia interna \u00fanicamente. No est\u00e1 afiliado ni avalado por Microsoft, y no es un examen ni certificaci\u00f3n real de Microsoft.",

      /* exam session */
      "exam.mode.cert": "Modo Certificaci\u00f3n", "exam.mode.practice": "Modo Pr\u00e1ctica",
      "exam.bar.question": "Pregunta", "exam.bar.of": "de", "exam.bar.answered": "respondidas",
      "exam.endPractice": "Finalizar pr\u00e1ctica",
      "exam.question": "Pregunta",
      "exam.chooseBest": "Elige la mejor respuesta.",
      "exam.prev": "\u2190 Anterior", "exam.next": "Siguiente \u2192",
      "exam.markReview": "Marcar para revisi\u00f3n",
      "exam.review.btn": "Revisi\u00f3n \u2630",
      "exam.reviewSubmit": "Revisar y enviar", "exam.finish": "Finalizar",
      "exam.reviewScreen": "Pantalla de revisi\u00f3n",
      "exam.review.title": "Revisa tus respuestas",
      "exam.review.note": "Selecciona cualquier pregunta para volver a ella. Los \u00edtems que marcaste aparecen se\u00f1alados. Las preguntas sin responder se puntan como incorrectas.",
      "exam.legend.answered": "Respondida", "exam.legend.unanswered": "Sin responder", "exam.legend.marked": "Marcada para revisi\u00f3n",
      "exam.allAnswered": "Todas las preguntas respondidas.",
      "exam.stillUnanswered1": "pregunta a\u00fan sin responder.", "exam.stillUnanswered2": "preguntas a\u00fan sin responder.",
      "exam.markedForReview": "marcadas para revisi\u00f3n.",
      "exam.returnQuestions": "\u2190 Volver a las preguntas",
      "exam.submit": "Enviar examen",
      "exam.confirm.unanswered1": "Tienes", "exam.confirm.unanswered2": "pregunta sin responder",
      "exam.confirm.unanswered2p": "preguntas sin responder",
      "exam.confirm.anyway": ". \u00bfEnviar de todos modos? Los \u00edtems sin responder se puntan como incorrectos.",
      "exam.confirm.submit": "\u00bfEnviar tu examen para puntuaci\u00f3n?",
      "exam.confirm.endPractice": "\u00bfFinalizar esta sesi\u00f3n de pr\u00e1ctica y ver tus resultados?",

      /* exam report */
      "exam.attempt": "Intento de certificaci\u00f3n", "exam.session": "Sesi\u00f3n de pr\u00e1ctica",
      "exam.pass": "APROBADO", "exam.fail": "NO APROBADO",
      "exam.passingScore": "Puntaje de aprobaci\u00f3n:",
      "exam.passLine": "aprobaci\u00f3n",
      "exam.correctSuffix": "correctas",
      "exam.ofCorrect": "correctas \u00b7 tiempo usado",
      "exam.timeExpired": "Tiempo agotado \u00b7",
      "exam.attemptedOn": "Realizado el",
      "exam.breakdown.title": "Desempe\u00f1o por \u00e1rea de competencia",
      "exam.answers.review": "Revisar todas las preguntas y explicaciones",
      "exam.answers.hide": "Ocultar revisi\u00f3n de preguntas",
      "exam.retakeCert": "Repetir examen de certificaci\u00f3n", "exam.newPractice": "Nueva sesi\u00f3n de pr\u00e1ctica",
      "exam.backModules": "Volver a los m\u00f3dulos",
      "exam.answer.correct": "Correcta", "exam.answer.incorrect": "Incorrecta", "exam.answer.unanswered": "Sin responder",
      "exam.answer.markCorrect": " \u2713 Respuesta correcta", "exam.answer.markYour": " \u2715 Tu respuesta", "exam.answer.markYourCorrect": " \u2713 Tu respuesta",
      "exam.answer.explanation": "Explicaci\u00f3n:",
      "exam.noQuestions": "No hay preguntas disponibles.",

      /* group / stage / belt display names */
      "group.Foundations": "Fundamentos",
      "group.Methodologies & Cycles": "Metodolog\u00edas & Ciclos",
      "group.Value & Quality Definition": "Definici\u00f3n de Valor & Calidad",
      "group.Process Mapping & Analysis": "Mapeo & An\u00e1lisis de Procesos",
      "group.Workplace, Flow & Standardization": "Lugar de Trabajo, Flujo & Estandarizaci\u00f3n",
      "group.Measurement & Control": "Medici\u00f3n & Control",
      "group.Strategy & Governance": "Estrategia & Gobernanza",

      "stage.1": "Etapa 1 \u00b7 Empieza Aqu\u00ed \u2014 Qu\u00e9 es la MC",
      "stage.2": "Etapa 2 \u00b7 Ver el Valor y el Desperdicio",
      "stage.3": "Etapa 3 \u00b7 Organizar y Estandarizar",
      "stage.4": "Etapa 4 \u00b7 Mejorar en Ciclos",
      "stage.5": "Etapa 5 \u00b7 Mapear y Analizar el Proceso",
      "stage.6": "Etapa 6 \u00b7 Encontrar la Causa Ra\u00edz",
      "stage.7": "Etapa 7 \u00b7 Equilibrar el Flujo",
      "stage.8": "Etapa 8 \u00b7 Medir con Datos",
      "stage.9": "Etapa 9 \u00b7 Comprobarlo Estad\u00edsticamente",
      "stage.10": "Etapa 10 \u00b7 Liderar y Gobernar",

      "belt.white.name": "Cintur\u00f3n Blanco", "belt.white.tagline": "Conciencia & vocabulario",
      "belt.white.goal": "Conoce el lenguaje de la mejora continua y reconoce las herramientas centrales \u2014 entiendes qu\u00e9 son y por qu\u00e9 importan, incluso antes de aplicarlas.",
      "belt.yellow.name": "Cintur\u00f3n Amarillo", "belt.yellow.tagline": "Practicante \u2014 contribuye a las mejoras",
      "belt.yellow.goal": "Participa en eventos de mejora: aplica los 5 Porqu\u00e9s a un problema confirmado, contribuye a un Ishikawa y apoya el trabajo est\u00e1ndar y la prueba de errores.",
      "belt.green.name": "Cintur\u00f3n Verde", "belt.green.tagline": "Lidera proyectos peque\u00f1os a medianos",
      "belt.green.goal": "Lleva proyectos DMAIC de principio a fin con mapeo de procesos, equilibrado de flujo y estad\u00edstica b\u00e1sica.",
      "belt.black.name": "Cintur\u00f3n Negro", "belt.black.tagline": "Lidera programas, mentorea & gobierna",
      "belt.black.goal": "Lidera programas multifuncionales con estad\u00edstica avanzada, an\u00e1lisis de riesgo y estrategia de MC \u2014 y mentorea a los Cinturones Verdes.",
      "belt.hoursSuffix": "horas",

      "domain.foundations": "Describir los fundamentos y conceptos de la mejora continua",
      "domain.methods": "Aplicar metodolog\u00edas y ciclos de mejora",
      "domain.value": "Definir el valor y la calidad para el cliente",
      "domain.mapping": "Mapear y analizar procesos y causas ra\u00edz",
      "domain.flow": "Optimizar el lugar de trabajo, el flujo y la estandarizaci\u00f3n",
      "domain.measure": "Medir y controlar procesos estad\u00edsticamente",
      "domain.govern": "Liderar la estrategia y gobernanza de MC",

      /* feedback (Voice of Customer) */
      "voc.button": "Comentarios",
      "voc.aria": "Comparte tus comentarios",
      "voc.title": "Comparte tus comentarios",
      "voc.lede": "Ay\u00fadanos a mejorar la Serie de Entregas de 30 Minutos. Tus comentarios se recopilan como una incidencia de Voz del Cliente (VOC) en el repositorio de GitHub del proyecto.",
      "voc.github.note": "Al enviar, se abre una incidencia de GitHub ya rellenada en una pesta\u00f1a nueva &mdash; rev\u00edsala y haz clic en <strong>Submit new issue</strong> para enviarla. Se requiere una cuenta de GitHub con acceso al repositorio.",
      "voc.type.label": "\u00bfQu\u00e9 tipo de comentario es este?",
      "voc.type.content": "Exactitud del contenido",
      "voc.type.suggestion": "Sugerencia o mejora",
      "voc.type.bug": "Error o enlace roto",
      "voc.type.question": "Pregunta",
      "voc.type.praise": "Elogio",
      "voc.type.other": "Otro",
      "voc.rating.label": "Calificaci\u00f3n general (opcional)",
      "voc.rating.clear": "Borrar calificaci\u00f3n",
      "voc.subject.label": "Resumen",
      "voc.subject.ph": "Un t\u00edtulo corto para tu comentario",
      "voc.details.label": "Detalles",
      "voc.details.ph": "Qu\u00e9 funcion\u00f3, qu\u00e9 no y cualquier sugerencia\u2026",
      "voc.name.label": "Tu nombre (opcional)",
      "voc.name.ph": "Para dar seguimiento, si es necesario",
      "voc.required": "Agrega un resumen y algunos detalles antes de enviar.",
      "voc.submit": "Abrir incidencia en GitHub",
      "voc.cancel": "Cancelar",
      "survey.exam.eyebrow": "Encuesta r\u00e1pida",
      "survey.exam.title": "\u00bfQu\u00e9 te pareci\u00f3 esta evaluaci\u00f3n?",
      "survey.exam.lede": "Unas preguntas r\u00e1pidas nos ayudan a mejorar el examen de pr\u00e1ctica CI-900.",
      "survey.exam.q.label": "\u00bfC\u00f3mo sentiste la dificultad?",
      "survey.exam.q.easy": "Demasiado f\u00e1cil",
      "survey.exam.q.right": "En su punto",
      "survey.exam.q.hard": "Demasiado dif\u00edcil",
      "survey.belt.eyebrow": "Cintur\u00f3n completado \u00b7 Encuesta r\u00e1pida",
      "survey.belt.title": "Llegaste al final del plan {belt}",
      "survey.belt.lede": "\u00a1Felicidades! Cu\u00e9ntanos c\u00f3mo te result\u00f3 este cintur\u00f3n para poder mejorarlo.",
      "survey.belt.q.label": "\u00bfQu\u00e9 tan seguro(a) te sientes para aplicar estas herramientas?",
      "survey.belt.q.low": "A\u00fan sin confianza",
      "survey.belt.q.mid": "En camino",
      "survey.belt.q.high": "Con confianza",
      "survey.rating.label": "En general, \u00bfqu\u00e9 calificaci\u00f3n le dar\u00edas?",
      "survey.comment.label": "\u00bfAlgo que quieras agregar? (opcional)",
      "survey.comment.ph": "Qu\u00e9 funcion\u00f3, qu\u00e9 no y cualquier sugerencia\u2026",
      "survey.github.note": "Al enviar se abre una incidencia de GitHub previamente rellenada en una pesta\u00f1a nueva &mdash; rev\u00edsala y haz clic en <strong>Submit new issue</strong> para enviarla. Se requiere una cuenta de GitHub con acceso al repositorio.",
      "survey.required": "Agrega una calificaci\u00f3n general antes de enviar.",
      "survey.submit": "Enviar encuesta",
      "survey.dismiss": "Ahora no",
      "survey.thanks.title": "\u00a1Gracias!",
      "survey.thanks.body": "Tus comentarios nos ayudan a mejorar la Serie de Entregas de 30 Minutos."
    }
  };

  function t(key) {
    var lang = getLang();
    var table = DICT[lang] || DICT.en;
    if (Object.prototype.hasOwnProperty.call(table, key)) return table[key];
    if (Object.prototype.hasOwnProperty.call(DICT.en, key)) return DICT.en[key];
    return key;
  }

  /* ---------------- Static HTML population ---------------- */
  function applyStatic(scope) {
    var root = scope || document;
    var lang = getLang();
    document.documentElement.lang = lang === "pt-BR" ? "pt-BR" : (lang === "es-419" ? "es-419" : "en");
    Array.prototype.forEach.call(root.querySelectorAll("[data-i18n]"), function (node) {
      var v = t(node.getAttribute("data-i18n"));
      if (v != null) node.textContent = v;
    });
    Array.prototype.forEach.call(root.querySelectorAll("[data-i18n-html]"), function (node) {
      var v = t(node.getAttribute("data-i18n-html"));
      if (v != null) node.innerHTML = v;
    });
    Array.prototype.forEach.call(root.querySelectorAll("[data-i18n-aria-label]"), function (node) {
      var v = t(node.getAttribute("data-i18n-aria-label"));
      if (v != null) node.setAttribute("aria-label", v);
    });
    var titleKey = document.documentElement.getAttribute("data-i18n-title");
    if (titleKey) { var tv = t(titleKey); if (tv != null) document.title = tv; }
  }

  window.SmartCI = {
    getLang: getLang,
    setLang: setLang,
    locale: locale,
    langName: langName,
    t: t,
    fmtNumber: fmtNumber,
    fmtPercent: fmtPercent,
    fmtDate: fmtDate,
    getModules: getModules,
    applyStatic: applyStatic
  };

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", function () { applyStatic(); });
  } else {
    applyStatic();
  }
})();
